# Default common configs

defaults:
  # Add common items
  - scenario_builder: nuplan_mini
  - scenario_filter: one_continuous_log
  - model: null
  # Worker that is used to run simulations
  - worker: ray_distributed

distribute_by_scenario: true

selected_simulation_metrics: null

# Sets verbosity level, in particular determines if progress bars are shown or not.
verbose: false
