defaults:
  - common:
      - ego_lane_change_statistics
      - ego_progress_along_expert_route_statistics
      - ego_jerk_statistics
      - ego_lat_acceleration_statistics
      - ego_lon_acceleration_statistics
      - ego_lon_jerk_statistics
      - ego_yaw_acceleration_statistics
      - ego_yaw_rate_statistics
  - high_level_common:  # High level common metric that depends on lower level metrics, they can also rely on the previously called high level metrics
      - drivable_area_violation_statistics
      - ego_at_fault_collisions_statistics
      - ego_at_fault_collisions_with_bicycles_statistics
      - ego_at_fault_collisions_with_vehicles_statistics
      - ego_at_fault_collisions_with_pedestrians_statistics
      - ego_at_fault_collisions_with_objects_statistics
      - time_to_collision_statistics
      - speed_limit_violation_statistics
      - ego_is_comfortable_statistics
